base_config: ./config/
base_expid: DCNv3_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 10000
    num_deep_cross_layers: [4]
    num_shallow_cross_layers: [3, 4, 5, 6]


